experiment_name: exp001B_v2.1_gemma2_model_scale_t4
model_dir: /content/drive/MyDrive/EdgeLLM-Systems/models
result_dir: /content/drive/MyDrive/EdgeLLM-Systems/results/exp001B/temp
exp_info_dir: /content/drive/MyDrive/EdgeLLM-Systems/results/exp001B/temp/exp_info
torch_dtype: float16
device_map: gpu_only

repeat: 3
base_prompt: "The quick brown fox jumps over the lazy dog. "

default_model_choice: Gemma 2 2B IT
default_prompt_lengths: [64, 128, 256, 512, 1024, 2048]
default_gen_lengths: [32, 64, 128]
prompt_len_options: [64, 128, 256, 512, 1024, 2048, 4096, 8192]
gen_len_options: [16, 32, 64, 128]